const CONFIG = {
    introTitle: 'Em à!',
    introDesc: `Hôm nay là sinh nhật em rồi`,
    btnIntro: 'hihi',
    title: 'Cảm ơn em đã đến bên anh!',
    desc: 'Mãi bên nhau bạn nhé, yêu',
    btnYes: 'Vẫn cứ là thích anh <33',
    btnNo: 'Không, Anh trai à :3',
    question:'Trên thế giới hơn 7 tỉ người mà sao em lại yêu anh <3',
    btnReply: 'Gửi cho anh <3',
    reply: 'Yêu thì yêu mà không yêu thì yêu <33333333',
    mess: 'Anh biết mà 🥰. Yêu em nhiều nhiều 😘😘',
    messDesc: 'Tối nay 7h anh qua đón nhé công chúa.',
    btnAccept: 'Okiiiii lun <3',
}
